name: ci

on:
  push:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: os:${{ matrix.os }}|bazel|workspace:${{ hashFiles('WORKSPACE') }}
        restore-keys: |
          os:${{ matrix.os }}|bazel|workspace:

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install bazelisk
      run: npm install -g @bazel/bazelisk

    - name: Build
      run: bazelisk -c opt build //...
    - name: Test
      run: bazelisk -c opt test //...
